In [2]:
import pandas as pd

### Liar Fake News Detection

https://www.kaggle.com/datasets/mubarakdaha/liar-fake-news-detection

In [3]:
liar_fake_news_detection = pd.read_csv("../data/liar_fake_news_detection/myfile.csv")

In [4]:
liar_fake_news_detection.head(10)

                                                text label
0  Democratic National Committee Chair Debbie Was...     0
1  ANKARA (Reuters) - Many Iranians who dreamt of...     1
2  This video brilliantly dispels every one of Hi...     0
3  DES MOINES, Iowa (Reuters) - U.S. Democratic p...     1
4  ABU DHABI (Reuters) - - Hillary Clinton’s vict...     1
5  Donald Trump and his team are getting absolute...     0
6  WASHINGTON (Reuters) - The U.S. Department of ...     1
7  WASHINGTON (Reuters) - The United States carri...     1
8  WASHINGTON (Reuters) - U.S. Defense Secretary ...     1
9  Donald Trump has a strategy to defeat Hillary ...     0

In [5]:
liar_fake_news_detection["label"].value_counts()

label
0                                                                                                                                                                                                                                                                                                                                                                       23432
1                                                                                                                                                                                                                                                                                                                                                                       21400
 another controversial nugget in the JFK files was a memo written by FBI Director Hoover after Oswald was shot by Ruby. The memo revealed that the head of FBI was concerned that the bureau needed to  convince  the public that Oswald acted alone in the Kennedy assassination. A portion of Hoover s memo read The thing I am concerned about                           2
 we see Mickey and Mallory driving in an RV as parents. The idea here is that the Knoxes represent a future society                                                                                                                                                                                                                                                         2
 chance and human agency. We have only to reflect upon defunct glacial despotisms such as the USSR or East Germany to realize that nothing is forever.Throughout history                                                                                                                                                                                                    2
 while criticizing their conservative counterparts.National Committee for Voting Integrity: This group opposes  the implementation of proof of citizenship and photo identification requirements for eligible electors in American elections as the means of assuring election integrity. National Council for Research on Women: This group supports big government        2
 it s certainly an old lesson by now. Depending on what your view of communism is                                                                                                                                                                                                                                                                                           1
 Democratic Congressman Barney Frank                                                                                                                                                                                                                                                                                                                                        1
 it s much easier to scapegoat an existential enemy for every systemic and institutional crisis affecting America. Whole industries have been spun out of this old habit: the intelligence industry                                                                                                                                                                         1
 which owns the Mandalay Bay hotel near where the shooting occurred                                                                                                                                                                                                                                                                                                         1
 like the fraudulent story published in The Post                                                                                                                                                                                                                                                                                                                            1
 and is heavily funded by Democracy Alliance                                                                                                                                                                                                                                                                                                                                1
Name: count, dtype: int64

In [6]:
liar_fake_news_detection["label"].astype(str)
liar_fake_news_detection.dtypes

text     str
label    str
dtype: object

In [7]:
liar_fake_news_detection = liar_fake_news_detection[liar_fake_news_detection["label"].isin(["0", "1"])]
liar_fake_news_detection["label"].value_counts()

label
0    23432
1    21400
Name: count, dtype: int64

In [8]:
liar_fake_news_detection.to_csv("../data/datasets/liar_dataset.csv")

In [11]:
pd.set_option("display.max_colwidth", None)
liar_fake_news_detection[liar_fake_news_detection["label"] == "0"].head()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            text  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Democratic National Committee Chair Debbie Wasserman Schultz is stepping down as chair of the DNC, effective the second she gavels the Philadelphia convention closed.  This move comes on the heels of DNC insider emails that were leaked that appear to show that the DNC was in the tank for for former Secretary of State Hillary Clinton to win the Democratic nomination over unlikely rival Vermont Senator Bernie Sanders. The leaked documents were simply the straw that broke the camel s back, though. Wasserman Schulz has been a divisive figure within the party leadership for sometime now, and after this Democratic leaders decided that she had to go. Wasserman Schultz says of the decision: Going forward, the best way for me to accomplish those goals [which include electing Clinton president] is to step down as Party Chair at the end of this convention. As Party Chair, this week I will open and close the Convention and I will address our delegates about the stakes involved in this election not only for Democrats, but for all Americans. Wasserman Schultz will now speak on Monday afternoon, though originally she had been removed from all speaking slots at the Democrats  big event. However, it seems that her supporters, and even the outgoing DNC chair herself fought for her right to be able to speak. Senator Sanders had this to say on the subject:What does this mean for the Democratic Party? It means more party unity, that s what. We cannot win in November   or any other election   if the party splits. In the beginning, everyone underestimated the power of Sen. Sanders  message, and it seems that rank and file, establishment Democrats and party leaders saw him and his supporters as a distraction and an annoyance rather than someone whose ideas and policy proposals should be taken seriously. This was a mistake. We can never assume that everyone is as loyal to any political party as said party s leadership would like them to be.Now, as a firm Clinton supporter, I have had my issues with Bernie Sanders and his supporters. However, party unity and beating Donald Trump is the top priority, not petty infighting. Sanders had great influence over this year s party platform- the most progressive in the party s history   and he and his supporters should be proud of what they have accomplished.Now that DWS is out of our way, let s go forth and kick butt and elect Democrats from the top of the ballot down in November.Feataured image via Andrew Burton/Getty Images
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                This video brilliantly dispels every one of Hillary s false claims and throws them right back in her face Absolutely brilliant!